#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jsr166e
Version  : 1.1.0
Release  : 1
URL      : https://github.com/twitter-archive/jsr166e/archive/v1.1.0.tar.gz
Source0  : https://github.com/twitter-archive/jsr166e/archive/v1.1.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.jar
Source2  : https://repo.maven.apache.org/maven2/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0
Requires: mvn-jsr166e-data = %{version}-%{release}
Requires: mvn-jsr166e-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
## JSR166e [![Build Status](https://secure.travis-ci.org/twitter/jsr166e.png?branch=master)](http://travis-ci.org/twitter/jsr166e)

%package data
Summary: data components for the mvn-jsr166e package.
Group: Data

%description data
data components for the mvn-jsr166e package.


%package license
Summary: license components for the mvn-jsr166e package.
Group: Default

%description license
license components for the mvn-jsr166e package.


%prep
%setup -q -n jsr166e-1.1.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jsr166e
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-jsr166e/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.jar
/usr/share/java/.m2/repository/com/twitter/jsr166e/1.1.0/jsr166e-1.1.0.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jsr166e/LICENSE
